const productos = [
  {
    id: 1,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Carolina Herrera",
    nombre: "Good-Girl",
    tamanio: 100,
    precio: 10800,
    codigo: 7798656800,
    stock: 2,
    foto: "goodGirlCH.jpg",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 2,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Ralph Lauren",
    nombre: "Ralph",
    tamanio: 80,
    precio: 9800,
    codigo: 7798656810,
    stock: 3,
    foto: "ralphLaurenEDTMujer.jpg",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 3,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Paco Rabanne",
    nombre: "Black-XS",
    tamanio: 80,
    precio: 9600,
    codigo: 7798656820,
    stock: 1,
    foto: "pacoRBlackXSMujer.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 4,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Lancome",
    nombre: "Idole",
    tamanio: 75,
    precio: 14600,
    codigo: 7798656830,
    stock: 3,
    foto: "idole.jpg",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 5,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Yves Saint Laurent",
    nombre: "Opium-Black",
    tamanio: 100,
    precio: 11600,
    codigo: 7798656840,
    stock: 5,
    foto: "BlackOpiumYvesSLMujer.jpg",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 6,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Nina-Ricci",
    nombre: "Ruge",
    tamanio: 80,
    precio: 11600,
    codigo: 7798656850,
    stock: 2,
    foto: "ninaRougeMujer.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 7,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Cacharel",
    nombre: "Anais-Anais",
    tamanio: 50,
    precio: 9200,
    codigo: 7798656860,
    stock: 1,
    foto: "AnaisAnaisCacha.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 8,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Calvin Klein",
    nombre: "Eternity",
    tamanio: 120,
    precio: 10600,
    codigo: 7798656870,
    stock: 2,
    foto: "calvinKleinEternMujer.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 9,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Tommy Hilfiger",
    nombre: "Tommy-Girl",
    tamanio: 100,
    precio: 11200,
    codigo: 7798656880,
    stock: 1,
    foto: "tommyGirl.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 10,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Givenchy",
    nombre: "L´interdit",
    tamanio: 50,
    precio: 10700,
    codigo: 7798656890,
    stock: 1,
    foto: "linterditGivenchyMujer.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 11,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Dior",
    nombre: "Jador",
    tamanio: 100,
    precio: 14600,
    codigo: 7798656900,
    stock: 5,
    foto: "JadorDior.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 12,
    quantity: 1,
    categoria: "perfumeria",
    marca: "Kenzo",
    nombre: "L´eau-Kenzo",
    tamanio: 75,
    precio: 10200,
    codigo: 7798656910,
    stock: 3,
    foto: "LeauKenzoMujer.png",
    descripcion:
      "Notas de Salida son almendra, café, bergamota y limón. Notas de Corazón son nardos, jazmín sambac (sampaguita), raíz de lirio, flor de azahar del naranjo y rosa de Bulgaria (rosa Damascena de Bulgaria).Notas de Fondo son haba tonka, cacao, vainilla, praliné, sándalo, ámbar, almizcle, madera de cachemira, pachulí, canela y cedro.",
  },
  {
    id: 13,
    quantity: 1,
    categoria: "farmacia",
    marca: "Roemmers",
    nombre: "Sertal Perlas",
    tamanio: 10,
    precio: 200,
    codigo: 7798657000,
    stock: 2,
    foto: "sertalPerlas.png",
    descripcion: "Antiespasmódico, analgésico",
  },
  {
    id: 14,
    quantity: 1,
    categoria: "farmacia",
    marca: "Bayer",
    nombre: "Actron 400",
    tamanio: 10,
    precio: 300,
    codigo: 7798657002,
    stock: 5,
    foto: "actron400.jpg",
    descripcion:
      "Ibuprofeno. Alivia los dolores asociados a estados gripales, resfrío común y para bajar la fiebre.",
  },
  {
    id: 15,
    quantity: 1,
    categoria: "farmacia",
    marca: "Elea",
    nombre: "Tafirol Plus",
    tamanio: 8,
    precio: 280,
    codigo: 7798657004,
    stock: 5,
    foto: "tafirolPlus.jpg",
    descripcion: "Paracetamol y Diclofenac.",
  },
  {
    id: 16,
    quantity: 1,
    categoria: "farmacia",
    marca: "Atom",
    nombre: "Barbijo Atom Protect",
    tamanio: 3,
    precio: 450,
    codigo: 7798657006,
    stock: 5,
    foto: "barbijoAtom.jpg",
    descripcion:
      "Barbijo con Nanotecnología, dura 15 lavados. Talle 1->6-9años, Talle 2->9-12, Talle 3->Adultos",
  },
  {
    id: 17,
    quantity: 1,
    categoria: "oferta",
    marca: "Bagovit 2x1",
    nombre: "Bagovit Solar",
    tamanio: 300,
    precio: 450,
    codigo: 7798657009,
    stock: 10,
    foto: "oferta1.png",
    descripcion: "Protector Solar.",
  },
  {
    id: 18,
    quantity: 1,
    categoria: "oferta",
    marca: "Cicatrcure 2x1",
    nombre: "Cicatricure Anti-Edad",
    tamanio: 50,
    precio: 1450,
    codigo: 7798657010,
    stock: 10,
    foto: "oferta2.png",
    descripcion: "Reduce lineas de exprecion y arrugas.",
  },
  {
    id: 19,
    quantity: 1,
    categoria: "oferta",
    marca: "Nivea 2x1",
    nombre: "Toallitas desmaquillantes Nivea",
    tamanio: 30,
    precio: 450,
    codigo: 7798657011,
    stock: 10,
    foto: "oferta3.png",
    descripcion: "Limpieza diaria.",
  },
  {
    id: 20,
    quantity: 1,
    categoria: "oferta",
    marca: "Livopen",
    nombre: "Livopen",
    tamanio: 50,
    precio: 450,
    codigo: 7798657012,
    stock: 10,
    foto: "oferta5.png",
    descripcion: "Repelente de mosquitos.",
  },
  {
    id: 21,
    quantity: 1,
    categoria: "dermocosmetica",
    marca: "Artez Westerley",
    nombre: "Hidratación Inteligente",
    tamanio: 50,
    precio: 2250,
    codigo: 7798657013,
    stock: 5,
    foto: "serumAW.png",
    descripcion: "Serum hidratación profunda.",
  },
  {
    id: 22,
    quantity: 1,
    categoria: "dermocosmetica",
    marca: "Artez Westerley",
    nombre: "Aminocelular Nutritiva",
    tamanio: 50,
    precio: 3450,
    codigo: 7798657014,
    stock: 10,
    foto: "aminocelularNutritivaAW.png",
    descripcion: "Crema de noche.",
  },
  {
    id: 23,
    quantity: 1,
    categoria: "dermocosmetica",
    marca: "Artez Westerley",
    nombre: "Anti-Age",
    tamanio: 50,
    precio: 3450,
    codigo: 7798657015,
    stock: 10,
    foto: "AntoageNutriPielSecaAW.png",
    descripcion: "Crema para todos los días.",
  },
  {
    id: 24,
    quantity: 1,
    categoria: "dermocosmetica",
    marca: "Laroche-posay",
    nombre: "Hyalu B5",
    tamanio: 50,
    precio: 6450,
    codigo: 7798657016,
    stock: 1,
    foto: "hyalub5.png",
    descripcion: "Serum con Acido Hyaluronico.",
  },
  {
    id: 25,
    quantity: 1,
    categoria: "dermocosmetica",
    marca: "Laroche-posay",
    nombre: "Vitamina C10",
    tamanio: 50,
    precio: 6450,
    codigo: 7798657017,
    stock: 1,
    foto: "vitc10.png",
    descripcion: "Serum con vitamina C.",
  },
];

export default productos;
